apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  namespace: kokiri
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - image: "harbor.molygoo.com/yahaha/kokiri-feedback:main-f5aef662"
          name: feedback
          ports:
            - name: tcp-20982
              containerPort: 20982
              protocol: TCP
            - name: tcp-50052
              containerPort: 50052
              protocol: TCP
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: APOLLO_CONFIG_SERVICE
              value: "http://172.18.190.169:18080"
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
      imagePullSecrets:
        - name: harbor-molygoo-reg