apiVersion: apps/v1
kind: Service
metadata:
  name: gateway
  namespace: kokiri
  labels:
    app: gateway
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31825
  selector:
    app: gateway
  type: nodePort
  ipFamilies:
    - IPv4
  
