apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashtag
  namespace: kokiri
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hashtag
  template:
    metadata:
      labels:
        app: hashtag
    spec:
      containers:
        - image: "harbor.molygoo.com/yahaha/kokiri-hashtag:feat-common-ez-db66c1e3"
          name: hashtag
          ports:
            - name: tcp-20982
              containerPort: 20982
              protocol: TCP
            - name: tcp-50052
              containerPort: 50052
              protocol: TCP
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: APOLLO_CONFIG_SERVICE
              value: "http://172.18.190.169:18080"
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 1Gi
      imagePullSecrets:
        - name: harbor-molygoo-reg